apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- deployment.yaml
- service.yaml
- ingress.yaml
- hpa.yaml
- servicemonitor.yaml

namespace: devopspro

images:
- name: goapp
  newName: rampss/argocd
  newTag: b6e5895c01f547f834e5e995aa56980c307e7d56
