grafana:
  adminPassword: admin
  enabled: true
  
  ingress:
    enabled: true
    ingressClassName: nginx
    
    annotations:
      kubernetes.io/ingress.class: nginx
    
    hosts:
      - grafana.127.0.0.1.nip.io
   
    path: /


prometheus:
  ingress:

    enabled: true

    ingressClassName: nginx
    annotations: 
      nginx.ingress.kubernetes.io/rewrite-target: /
    hosts:
      - prometheus.127.0.0.1.nip.io

    paths:
      - /
    
alertmanager:
  ingress:

    enabled: true

    ingressClassName: nginx
    annotations: 
      kubernetes.io/ingress.class: nginx
    hosts:
      - alertmanager.127.0.0.1.nip.io

    paths:
      - /
