resources:
- ../../base
# App config custom
  # Patch para o Ingress
  # Patch para o Deployment
  # Patch para o Namespace
patches:
- path: ./patches/host-patch.yaml
  target:
    kind: Ingress
    name: goapp-ingress
- path: ./patches/resources-patch.yaml
  target:
    kind: Deployment
    name: goapp
- path: ./patches/namespace-patch.yaml
  target:
    kind: Deployment
    name: goapp
- path: ./patches/namespace-patch.yaml
  target:
    kind: Ingress
    name: goapp-ingress
- path: ./patches/namespace-patch.yaml
  target:
    kind: Service
    name: goapp
- path: ./patches/namespace-patch.yaml
  target:
    kind: HorizontalPodAutoscaler
    name: goapp-hpa
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
images:
- name: goapp
  newName: rampss/argocd
  newTag: 307ebf919899c5cd157f951286a36659624e6e51
