name: CD
on:
  push:
    branches: [main]
  workflow_dispatch: # Permite execução manual para rollback

env:
  REPO: rampss/argocd

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Build Image and Push to Docker Hub
        uses: docker/build-push-action@v1.1.0
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
          repository: ${{ env.REPO }}
          tags: ${{ github.sha }}, latest

  deploy:
    name: Deploy
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      
      - name: Set Previous Commit SHA
        id: previous_commit
        run: |
          PREV_COMMIT=$(git rev-parse HEAD^)
          echo "previous_commit=$PREV_COMMIT" >> $GITHUB_ENV

      - name: Setup Kustomize
        uses: imranismail/setup-kustomize@v1
        with:
          kustomize-version: v3.6.1

      - name: Update K8s Image in Base
        run: |
          cd quickstart/base
          kustomize edit set image goapp=${{ env.REPO }}:${{ github.sha }}
          cat kustomization.yaml

      - name: Commit Changes
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "Deploy Action"
          git commit -am "Update image tag to ${{ github.sha }}" || echo "No changes to commit"

      - name: Push Changes
        uses: ad-m/github-push-action@master
        with:
          github_token: ${{ secrets.PERSONAL_TOKEN }}

  rollback:
    name: Rollback
    runs-on: ubuntu-latest
    if: github.event.inputs.rollback == 'true' # Executa apenas se chamado para rollback manualmente
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Setup Kustomize
        uses: imranismail/setup-kustomize@v1
        with:
          kustomize-version: v3.6.1

      - name: Rollback to Previous Commit
        run: |
          cd quickstart/base
          kustomize edit set image goapp=${{ env.REPO }}:${{ env.previous_commit }}
          cat kustomization.yaml

      - name: Commit Rollback Changes
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "Deploy Action"
          git commit -am "Rollback to previous commit ${{ env.previous_commit }}" || echo "No changes to commit"

      - name: Push Rollback Changes
        uses: ad-m/github-push-action@master
        with:
          github_token: ${{ secrets.PERSONAL_TOKEN }}
