name: CD
on:
  push:
    branches: [main]
  workflow_dispatch:
    inputs:
      rollback_tag:
        description: "Tag ou SHA da imagem para rollback"
        required: true

jobs:
  build:
    name: Build
    if: github.event_name == 'push'
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      
      - name: Build Image and Push to Docker Hub
        uses: docker/build-push-action@v1.1.0
        with:
          username: rampss
          password: ${{ secrets.DOCKER_PASSWORD }}
          repository: rampss/argocd
          tags: ${{ github.sha }}, latest

  deploy:
    name: Deploy
    if: github.event_name == 'push'
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Setup Kustomize
        uses: imranismail/setup-kustomize@v1
        with:
          kustomize-version: v3.6.1

      - name: Update K8s Image in Base
        run: |
          cd quickstart/base
          kustomize edit set image goapp=rampss/argocd:${{ github.sha }}
          cat kustomization.yaml

      - name: Commit Changes
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "Deploy Action"
          git commit -am "Update image tag to ${{ github.sha }}" || echo "No changes to commit"

      - name: Push Changes
        uses: ad-m/github-push-action@master
        with:
          github_token: ${{ secrets.PERSONAL_TOKEN }}

  rollback:
    name: Rollback
    if: github.event_name == 'workflow_dispatch'
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Setup Kustomize
        uses: imranismail/setup-kustomize@v1
        with:
          kustomize-version: v3.6.1

      - name: Rollback to Previous Tag
        run: |
          cd quickstart/base
          kustomize edit set image goapp=rampss/argocd:${{ github.event.inputs.rollback_tag }}
          cat kustomization.yaml

      - name: Commit Rollback
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "Rollback Action"
          git commit -am "Rollback to image tag ${{ github.event.inputs.rollback_tag }}" || echo "No changes to commit"

      - name: Push Rollback Changes
        uses: ad-m/github-push-action@master
        with:
          github_token: ${{ secrets.PERSONAL_TOKEN }}
